services:
  network-deploy-service:
    networks:
      - eazybank
  microservice-db-config:
    extends:
      service: network-deploy-service
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U posgres"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      POSTGRES_PASSWORD: root
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
      POSTGRES_USER: "posgres"
      POSTGRES_PASSWORD: "root"

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
